services:
  # === USERS ===
  users-db:
    image: postgres:15
    container_name: users_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - users_db_data:/var/lib/postgresql/data

  users_service:
    build: ./user-service
    container_name: users_service
    restart: always
    environment:
      DATABASE_URL: postgresql://admin:admin@users-db:5432/users_db?schema=public
    depends_on:
      - users-db
    command: sh -c "while true; do if [ -d prisma/migrations ] && [ \"$(ls -A prisma/migrations)\" ]; then npx prisma migrate deploy && break; else npx prisma db push --accept-data-loss && break; fi; echo 'Waiting for DB...'; sleep 1; done; npx prisma generate && node src/index.js"
  # === PRODUCTS ===
  products-db:
    image: postgres:15
    container_name: products_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: products_db
    ports:
      - "5433:5432"
    volumes:
      - products_db_data:/var/lib/postgresql/data

  products_service:
    build: ./products-service
    container_name: products_service
    restart: always
    environment:
      DATABASE_URL: postgresql://admin:admin@products-db:5432/products_db?schema=public
    depends_on:
      - products-db
    command: sh -c "while true; do if [ -d prisma/migrations ] && [ \"$(ls -A prisma/migrations)\" ]; then npx prisma migrate deploy && break; else npx prisma db push --accept-data-loss && break; fi; echo 'Waiting for DB...'; sleep 1; done; npx prisma generate && node src/index.js"

  # === ORDERS ===
  orders-db:
    image: mongo:7
    container_name: orders_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - orders_db_data:/data/db


  orders_service:
    build: ./orders-service
    container_name: orders_service
    restart: always
    env_file:
      - ./orders-service/.env
    environment:
      KAFKA_BROKERS: kafka:9092
    depends_on:
      orders-db:
        condition: service_started
      kafka:
        condition: service_healthy
    command: node src/index.js

  # === PAYMENTS ===
  payments-db:
    image: postgres:15
    container_name: payments_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payments_db
    ports:
      - "5437:5432"
    volumes:
      - payments_db_data:/var/lib/postgresql/data

  payments_service:
    build: ./payment-service
    container_name: payments_service
    restart: always
    environment:
      DATABASE_URL: postgresql://admin:admin@payments-db:5432/payments_db?schema=public
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      KAFKA_BROKERS: kafka:9092
    depends_on:
      payments-db:
        condition: service_started
      rabbitmq:
        condition: service_started
      kafka:
        condition: service_healthy
      orders_service:
        condition: service_started
      products_service:
        condition: service_started
    command: sh -c "while true; do if [ -d prisma/migrations ] && [ \"$(ls -A prisma/migrations)\" ]; then npx prisma migrate deploy && break; else npx prisma db push --accept-data-loss && break; fi; echo 'Waiting for DB...'; sleep 1; done; npx prisma generate && node src/index.js"

  # === NOTIFICATION ===
  notification_service:
    build: ./notification-service
    container_name: notification_service
    restart: always
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    depends_on:
      - rabbitmq
    command: node src/index.js

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  # === PGADMIN ===
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - users-db
      - products-db
      - payments-db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 5s
      timeout: 3s
      retries: 20

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  redis-cache:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
  
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander_lab
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis-cache:6379
    depends_on:
      - redis-cache

  # === API GATEWAY ===
  api-gateway:
    build: ./api-gateway
    container_name: api_gateway
    restart: always
    environment:
      REDIS_HOST: redis-cache
      REDIS_PORT: 6379
    depends_on:
      - redis-cache
      - users_service
      - products_service
      - orders_service
      - payments_service
    command: node src/index.js

  # === KONG (API Gateway) ===
  kong-db:
    image: postgres:15
    container_name: kong_db
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong_password
      POSTGRES_DB: kong
    volumes:
      - kong_postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  kong-migration:
    image: kong:3.4
    container_name: kong_migration
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong_password
    command: "kong migrations bootstrap"
    depends_on:
      - kong-db

  kong-gateway:
    image: kong:3.4
    container_name: kong_gateway
    restart: always
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong_password
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    depends_on:
      - kong-migration
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/" ]
      interval: 5s
      timeout: 3s
      retries: 20

  konga:
    image: pantsel/konga
    container_name: konga_ui
    restart: always
    environment:
      NODE_ENV: development
      KONGA_KONG_ADMIN_URL: http://kong-gateway:8001
    ports:
      - "1337:1337"
    depends_on:
      - kong-gateway

  kong-bootstrap:
    image: curlimages/curl:8.4.0
    container_name: kong_bootstrap
    depends_on:
      - kong-gateway
    volumes:
      - ./kong/bootstrap.sh:/bootstrap.sh:ro
    entrypoint: ["/bin/sh", "/bootstrap.sh"]

# === VOLUMES ===
volumes:
  users_db_data:
  products_db_data:
  orders_db_data:
  payments_db_data:
  pgadmin_data:
  redis_data:
  kong_postgres_data:

